version: "3.7"

services:
  db:
    image: postgres:14.2-alpine
    container_name: "sacculum_db"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"

  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "sacculum_api"
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/
