name: API Tests
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/**'
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Composer
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/

      - name: Run Behat tests
        run: |
          nohup php -S localhost:8080 -t src/ &
          ./vendor/bin/behat

      - name: Run phpcs
        run: ./vendor/bin/phpcs src/ && ./vendor/bin/phpcs tests/
